---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint:
  name: 'yamllint'
platforms:
  - name: "sysfs-docker-stretch"
    image: 'minimum2scp/systemd-stretch'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: "sysfs-docker-xenial"
    image: 'solita/ubuntu-systemd:16.04'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
    command: '/sbin/init'
  - name: "sysfs-docker-trusty"
    image: 'ubuntu:trusty'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: "sysfs-docker-bionic"
    image: 'solita/ubuntu-systemd:18.04'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
  inventory:
    group_vars:
      all:
        sysfs_rules:
          - filename: 'transparent-huge-pages.conf'
            rules:
              - key: 'kernel/mm/transparent_hugepage/defrag'
                value: 'never'
              - key: 'kernel/mm/transparent_hugepage/enabled'
                value: 'never'
    host_vars: {}
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  lint:
    name: 'flake8'
  options:
    sudo: True
